//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeRates.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.ExchangeRates = new HashSet<ExchangeRate>();
            this.ExchangeRates1 = new HashSet<ExchangeRate>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortForm { get; set; }
        public int Country_Id { get; set; }
        public string Description { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<ExchangeRate> ExchangeRates { get; set; }
        public virtual ICollection<ExchangeRate> ExchangeRates1 { get; set; }
    }
}
