//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeRates
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRate
    {
        public System.Guid Id { get; set; }
        public int Currency_Id { get; set; }
        public int BaseCurrency_Id { get; set; }
        public System.DateTime CurrencyDate { get; set; }
        public double Rate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
    }
}
