'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Index

   '''<summary>
   '''form1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

   '''<summary>
   '''StartDate control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents StartDate As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''EndDate control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents EndDate As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''list1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents list1 As Global.System.Web.UI.WebControls.DropDownList

   '''<summary>
   '''list2 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents list2 As Global.System.Web.UI.WebControls.DropDownList

   '''<summary>
   '''ErrorLabel control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ErrorLabel As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''SubmitButton control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents SubmitButton As Global.System.Web.UI.WebControls.Button
End Class
